"""Why is this outlet where it is? Show the reader actual headlines.

Evidence pages (METHODOLOGY.md D10): for every outlet, the stories that most
distinguish the two ends of the axis — which of them this outlet covered and
which it skipped, with real example headlines — plus its nearest neighbors
and its confidence interval. Generated by the same deterministic pipeline as
the scores; never hand-edited.
"""

from pathlib import Path

import numpy as np

from tiltmeter.signals.selection import first_axis  # same axis, story side

TOP_STORIES = 8


def _story_axis_coords(matrix: np.ndarray) -> np.ndarray:
    """Story (column) positions on the same axis the outlets were scaled on."""
    return first_axis(matrix.T)


def render(ratings: dict, stories: list, matrix: np.ndarray, articles: list) -> dict[str, str]:
    """Markdown evidence page per outlet, plus an index. Returns {filename: content}."""
    outlet_order = [o["outlet"] for o in sorted(ratings["outlets"], key=lambda o: o["score"])]
    scores = {o["outlet"]: o for o in ratings["outlets"]}
    # matrix rows follow manifest outlet order, which is sorted outlet names
    row_names = sorted(scores)
    row_index = {name: i for i, name in enumerate(row_names)}
    coords = _story_axis_coords(matrix)
    # align story-axis sign with outlet orientation: a story mostly covered by
    # right-scored outlets should sit at the right pole
    row_scores = np.array([scores[n]["score"] for n in row_names])
    covered_lean = (matrix.T @ row_scores) / np.maximum(matrix.sum(axis=0), 1.0)
    if float(np.dot(coords, covered_lean)) < 0:
        coords = -coords

    ranked_stories = np.argsort(coords)
    pages = {}
    headline = lambda i: f"[{articles[i]['outlet']}] {articles[i]['title']}"  # noqa: E731

    for name in outlet_order:
        row = row_index[name]
        entry = scores[name]
        neighbors = sorted(
            (o for o in ratings["outlets"] if o["outlet"] != name),
            key=lambda o: abs(o["score"] - entry["score"]),
        )[:3]
        lines = [
            f"# Evidence: {name}",
            "",
            f"- **Score**: {entry['score']:+.3f} "
            f"(95% CI {entry['ci_low']:+.3f} … {entry['ci_high']:+.3f}); "
            f"negative = left, positive = right",
            f"- **Snapshot**: {ratings['snapshot_id']} (corpus {ratings['corpus_hash'][:12]}…), "
            f"pipeline v{ratings['pipeline_version']}",
            f"- **Coverage**: {entry['stories_covered']} of {ratings['n_stories']} "
            f"cross-outlet stories",
            "- **Nearest neighbors**: "
            + ", ".join(f"{n['outlet']} ({n['score']:+.3f})" for n in neighbors),
            "",
            "The stories below are the most axis-distinguishing in this snapshot —",
            "the ones outlets' choices disagree about most. What this outlet covered",
            "and skipped among them is what placed it where it is.",
            "",
        ]
        # disjoint by construction: never let one story argue for both poles
        k = min(TOP_STORIES, len(ranked_stories) // 2)
        for label, indices in (
            ("Left-pole stories", ranked_stories[:k]),
            ("Right-pole stories", ranked_stories[::-1][:k]),
        ):
            lines.append(f"## {label}")
            lines.append("")
            for sid in indices:
                story = stories[int(sid)]
                mark = "covered" if matrix[row, int(sid)] else "skipped"
                lines.append(f"- **{mark}** — {headline(story.article_indices[0])}")
            lines.append("")
        pages[f"{name}.md"] = "\n".join(lines)

    index = [
        f"# Evidence pages — snapshot {ratings['snapshot_id']}",
        "",
        "Generated by the pipeline (never hand-edited). Reference frame: "
        + ratings["reference_frame"] + ".",
        "",
        "| Outlet | Score | 95% CI |",
        "|---|---|---|",
    ]
    for name in outlet_order:
        e = scores[name]
        index.append(
            f"| [{name}]({name}.md) | {e['score']:+.3f} | "
            f"{e['ci_low']:+.3f} … {e['ci_high']:+.3f} |"
        )
    pages["index.md"] = "\n".join(index) + "\n"
    return pages


def write(pages: dict[str, str], ratings: dict, out_dir: str | Path) -> Path:
    directory = Path(out_dir) / f"report-{ratings['snapshot_id']}"
    directory.mkdir(parents=True, exist_ok=True)
    for stale in directory.glob("*.md"):
        stale.unlink()  # regeneration must never leave pages from a prior run
    for filename, content in pages.items():
        (directory / filename).write_text(content, encoding="utf-8")
    return directory
